/**
 * Generated by scripts/purs-dts.mjs from output/App.Utils.Format/docs.json — do not edit.
 *
 * TypeScript resolves `#purs/App.Utils.Format` here via tsconfig `paths`;
 * bundlers resolve it to `output/` via the package `imports` field.
 */

/** Title-case a phrase, keeping minor words lowercase past the first. */
export declare const titleCase: (arg0: string) => string

/** Render an ISO-ish date string as MM/YYYY. */
export declare const formatMonthYear: (arg0: string) => string
