/**
 * Generated by scripts/purs-dts.mjs from output/App.Utils.Coder/docs.json — do not edit.
 *
 * TypeScript resolves `#purs/App.Utils.Coder` here via tsconfig `paths`;
 * bundlers resolve it to `output/` via the package `imports` field.
 */

/** PureScript data — opaque from TypeScript. */
export type CodeFormat = unknown

/** One rendered piece of output. `code` tokens map back to input chars. */
export type OutToken = { text: string, kind: string, srcStart: number, srcEnd: number }

export type TranscodeJs = { ok: boolean, error: string, output: string, bytes: (number)[], tokens: (OutToken)[] }

/** JS-friendly entry point: plain-string formats in a flat record, so the
TypeScript shim needs no knowledge of curried or ADT conventions. */
export declare const transcodeJs: (arg0: { input: string, from: string, to: string, preserveWhitespace: boolean }) => TranscodeJs

/** base64url-encode arbitrary text for share links. */
export declare const encodeShareText: (arg0: string) => string

/** Decode a share-link payload; null if malformed. */
export declare const decodeShareText: (arg0: string) => string | null
