/**
 * Generates TypeScript declarations for the compiled PureScript modules.
 *
 * Reads the typed AST spago emits per module (`output/<Module>/docs.json`)
 * and writes `app/types/purs/<Module>.d.ts`, so the TS boundary is derived
 * from the PureScript source instead of hand-maintained. Runs as part of
 * `bun run purs:build`.
 *
 * Translation subset (enough for a JS-friendly module boundary): prims,
 * arrays, records, curried functions, Nullable, and same-module synonyms.
 * ADTs are exported as opaque types; anything untranslatable is `unknown`.
 */

import { basename, dirname } from "node:path"
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const outDir = `${root}/app/types/purs`

const PRIMS = { String: "string", Int: "number", Number: "number", Boolean: "boolean", Char: "string" }

const translate = (t, locals) => {
  switch (t.tag) {
    case "TypeConstructor": {
      const [modulePath, name] = t.contents
      if (modulePath.length === 1 && modulePath[0] === "Prim" && PRIMS[name]) return PRIMS[name]
      if (locals.has(name)) return name
      return "unknown"
    }
    case "TypeApp": {
      const [head, arg] = t.contents
      if (head.tag === "TypeApp" && isCon(head.contents[0], "Prim", "Function")) {
        return `(arg0: ${translate(head.contents[1], locals)}) => ${translate(arg, locals)}`
      }
      if (isCon(head, "Prim", "Array")) return `(${translate(arg, locals)})[]`
      if (isCon(head, "Prim", "Record")) return translateRow(arg, locals)
      if (isCon(head, "Data.Nullable", "Nullable")) return `${translate(arg, locals)} | null`
      return "unknown"
    }
    case "ForAll":
      return translate(t.contents.at(-1), locals)
    case "ParensInType":
      return translate(t.contents, locals)
    default:
      return "unknown"
  }
}

const isCon = (t, modulePath, name) =>
  t.tag === "TypeConstructor" && t.contents[0].join(".") === modulePath && t.contents[1] === name

const translateRow = (row, locals) => {
  const fields = []
  let cursor = row
  while (cursor.tag === "RCons") {
    const [label, type, tail] = cursor.contents
    fields.push(`${label}: ${translate(type, locals)}`)
    cursor = tail
  }
  return `{ ${fields.join(", ")} }`
}

const docComment = (text) =>
  text ? `/** ${text.trim().replace(/\*\//g, "*\\/")} */\n` : ""

const generate = (docsPath) => {
  const docs = JSON.parse(readFileSync(docsPath, "utf8"))
  const moduleName = basename(dirname(docsPath))
  const locals = new Set(
    docs.declarations
      .filter(d => ["typeSynonym", "data", "newtype"].includes(d.info.declType))
      .map(d => d.title),
  )

  const lines = [
    "/**",
    ` * Generated by scripts/purs-dts.mjs from output/${moduleName}/docs.json — do not edit.`,
    " *",
    ` * TypeScript resolves \`#purs/${moduleName}\` here via tsconfig \`paths\`;`,
    " * bundlers resolve it to `output/` via the package `imports` field.",
    " */",
    "",
  ]

  for (const decl of docs.declarations) {
    const { declType } = decl.info
    if (declType === "typeSynonym") {
      lines.push(`${docComment(decl.comments)}export type ${decl.title} = ${translate(decl.info.type, locals)}`, "")
    } else if (declType === "data" || declType === "newtype") {
      lines.push(`/** PureScript ${declType} — opaque from TypeScript. */`, `export type ${decl.title} = unknown`, "")
    } else if (declType === "value") {
      lines.push(`${docComment(decl.comments)}export declare const ${decl.title}: ${translate(decl.info.type, locals)}`, "")
    }
  }

  const target = `${outDir}/${moduleName}.d.ts`
  writeFileSync(target, `${lines.join("\n").trim()}\n`)
  console.log(`generated ${target.replace(`${root}/`, "")}`)
}

mkdirSync(outDir, { recursive: true })
const moduleDocs = readdirSync(`${root}/output`)
  .filter(name => name.startsWith("App.") && existsSync(`${root}/output/${name}/docs.json`))
  .map(name => `${root}/output/${name}/docs.json`)
if (moduleDocs.length === 0) {
  console.error("no compiled App.* modules found — run `spago build` first")
  process.exit(1)
}
moduleDocs.sort().forEach(generate)
