/**
 * Generates the compiler-mandated FFI companion stubs.
 *
 * `purs` requires every module with `foreign import`s to have a sibling
 * `.js` file with the module's basename, and validates its named exports.
 * The stubs are fully mechanical — a named re-export of the module's
 * foreign values from the typed implementation in `app/ffi/<kebab>.ts`
 * (path relative to the compiled `.purs/output/<Module>/foreign.js`) — so they
 * are generated here (before `spago build`) and gitignored.
 */

import { basename, dirname, join } from "node:path"
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

const root = dirname(dirname(fileURLToPath(import.meta.url)))

const pursFiles = (dir: string): string[] => readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
  const path = join(dir, entry.name)
  if (entry.isDirectory()) return pursFiles(path)
  return entry.name.endsWith(".purs") ? [path] : []
})

const kebab = (s: string): string => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase()

for (const pursPath of pursFiles(`${root}/app`)) {
  const source = readFileSync(pursPath, "utf8")
  const names = [...source.matchAll(/^foreign import (data\s+)?([A-Za-z0-9_']+)/gm)]
    .filter(match => !match[1])
    .map(match => match[2])
  if (!names.length) continue

  const moduleBase = basename(pursPath, ".purs")
  const moduleName = source.match(/^module\s+([A-Za-z0-9.]+)/m)?.[1] ?? moduleBase
  // FFI files mirror the module path as subdirectories (minus the App
  // prefix), so same-basename modules in different namespaces never collide.
  const segments = moduleName.split(".")
  const ffiBase = (segments[0] === "App" ? segments.slice(1) : segments).map(kebab).join("/")
  const ffiPath = `${root}/app/ffi/${ffiBase}.ts`
  if (!existsSync(ffiPath)) {
    console.error(`missing FFI implementation app/ffi/${ffiBase}.ts for ${pursPath.replace(`${root}/`, "")}`)
    process.exit(1)
  }

  const stub = [
    "// Generated by scripts/purs-ffi-stubs.ts — do not edit.",
    `// Typed implementations live in app/ffi/${ffiBase}.ts (path relative to`,
    "// the compiled .purs/output/<Module>/foreign.js).",
    `export { ${names.sort().join(", ")} } from "../../../app/ffi/${ffiBase}.ts"`,
  ].join("\n")
  writeFileSync(`${dirname(pursPath)}/${moduleBase}.js`, `${stub}\n`)
  console.log(`generated ${dirname(pursPath).replace(`${root}/`, "")}/${moduleBase}.js`)
}
